# Generated by Django 4.1.7 on 2023-02-18 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Quarterbacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yards', models.IntegerField()),
                ('completions', models.IntegerField()),
                ('attempts', models.IntegerField()),
                ('completion_percentage', models.DecimalField(decimal_places=1, max_digits=3)),
                ('touchdowns', models.IntegerField()),
                ('touchdown_percentage', models.DecimalField(decimal_places=1, max_digits=3)),
                ('interceptions', models.IntegerField()),
                ('interception_percentage', models.DecimalField(decimal_places=1, max_digits=3)),
                ('first_downs_passing', models.IntegerField()),
                ('longest_completed_pass', models.IntegerField()),
                ('average_yards_per_attempt', models.DecimalField(decimal_places=1, max_digits=3)),
                ('adjusted_average_yards_per_attempt', models.DecimalField(decimal_places=1, max_digits=3)),
                ('yards_per_completion', models.DecimalField(decimal_places=1, max_digits=3)),
                ('yards_per_game', models.DecimalField(decimal_places=1, max_digits=3)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('times_sacked', models.IntegerField()),
                ('yards_lost_to_sacks', models.IntegerField()),
                ('sack_percentage', models.DecimalField(decimal_places=1, max_digits=3)),
                ('comebacks', models.IntegerField()),
                ('game_winning_drives', models.IntegerField()),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.positions')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.teams')),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('games', models.IntegerField()),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.positions')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.teams')),
            ],
        ),
    ]
