# Generated by Django 4.1.7 on 2023-02-19 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='players',
            old_name='games',
            new_name='games_played',
        ),
        migrations.AddField(
            model_name='players',
            name='games_started',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
