# Generated by Django 4.1.7 on 2023-02-19 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_rename_games_players_games_played_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='team',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
